In [1]:
import numpy as np
scalar=5
vector=np.array([1,2,3,4,5])
matrix=np.matrix([[1,2,2],[3,2,1],[1,2,3]])
print(scalar)
print(vector.ndim)
print(matrix.ndim)
print(np.linalg.matrix_rank(matrix))
# tensor- 3 or more dimensional value eg: [[[1,2],[2,3]],[[1,2],[2,3]]]

5
1
2
3


In [2]:
row=np.array([1,2,3])
col=np.matrix([[1],[2],[3]])
print(row.ndim)
print(col.ndim)
print(row)
print(col)

1
2
[1 2 3]
[[1]
 [2]
 [3]]


In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2], [3, 4]])
result = np.cross(A, B)
print(result)

[0 0]


C:\Users\thama\AppData\Local\Temp\ipykernel_13124\2393737085.py:3: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  result = np.cross(A, B)


In [7]:

A = np.array([[1, 2,3], [7,9,6]])
B = np.array([[4,5,6], [9,5,6]])
result = np.cross(A, B)
print(result)

[[ -3   6  -3]
 [ 24  12 -46]]


In [8]:
a=[1,2,3]
b=[4,5,6]
c=0
for i in range(len(a)):
    c+=(a[i]*b[i])  
print(c)    

32


In [9]:
a=[[1, 2, 3],[4, 5, 6]]
b=[]
for i in range(len(a[0])):
    c=[]
    for j in range(len(a)):
        c.append(a[j][i])
    b.append(c)
print("transpose of a matrix is:")    

for d in b:
    print(d)

transpose of a matrix is:
[1, 4]
[2, 5]
[3, 6]


In [5]:
A = np.array([1, 2,3, 4])
B = np.array([1, 2,3, 4])
result = np.dot(A, B)
print(result)

30


In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2], [3, 4]])
result = np.dot(A, B)
print(result)

[[ 7 10]
 [15 22]]


In [4]:
#transpose of a matrix
v1=np.array([[1,2],[3,4]])
print(v1.T)

[[1 3]
 [2 4]]
