In [ ]:
#mathmatical functions in ai
# linear algebra
# probability
# statistics
# hypothesis testing
# 
# #

In [ ]:
#arange function
#
import numpy as np  
n=np.arange(1,10)
print(n)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#linspace function
# linspace(start, stop, num=50, endpoint=True, retstep=False, dtype
n=np.linspace(0,1,10)
print(n)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#eye function
# eye(N, M=None, k=0, dtype=<class 'float'>)
# Returns a 2-D array with ones on the diagonal and zeros elsewhere.
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
#inverse of a matrix
import numpy as np
v1=np.matrix([[6,1,1],[4,-2,5],[2,8,7]])
print(v1)
print(np.linalg.inv(v1))

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [7]:
#determinant of matrix
v1=np.matrix([[6,1,1],[4,-2,5],[2,8,7]])
print(np.linalg.det(v1))

-306.0


In [ ]:
#pricpal component analysis
# PCA is a technique used to emphasize variation and bring out strong patterns in a dataset.

In [10]:
from numpy.linalg import eig
m= np.array([[4, 2], [1, 3]])
values, vectors = eig(m)
print("Eigenvalues:", values)
print("Eigenvectors:", vectors)

Eigenvalues: [5. 2.]
Eigenvectors: [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [17]:
a=np.random.rand(2,30)
print(a)

[[0.48857118 0.1437628  0.58068945 0.70578065 0.3830446  0.94531388
  0.07083016 0.79847954 0.22116658 0.30693094 0.53214462 0.90017824
  0.66269647 0.4790892  0.22181099 0.92196394 0.47262915 0.84465567
  0.14773609 0.27795763 0.00253949 0.38390933 0.72799079 0.40385996
  0.81633972 0.42513764 0.48001756 0.08369391 0.77118772 0.30469777]
 [0.25619085 0.01829629 0.13084222 0.89452634 0.75428917 0.62235918
  0.90334884 0.80665746 0.85799647 0.78771791 0.38717211 0.72794548
  0.36611889 0.11457835 0.33462747 0.30428632 0.44869329 0.51745011
  0.12970088 0.80916007 0.68688413 0.17176603 0.63543517 0.88435395
  0.16875984 0.88906263 0.12679222 0.77709783 0.3798619  0.3583931 ]]


In [18]:
v1=np.array([[1, 2], [3, 4]])


In [6]:
x=0
a=[1,2,3,4,5]
if a : x=a.val
print(x)

AttributeError: 'list' object has no attribute 'val'